#!/bin/bash
STATES="ak al ar az ca co ct dc de fl ga hi ia id il in ks ky la ma md me mi mn mo ms mt nc nd ne nh nj nm nv ny oh ok or pa pr ri sc sd tn tx ut va vt wa wi wv wy"
# LIMIT=0 for no limit
LIMIT=0
SF1DIR=/mnt/data/2010_sf1/geo
/bin/rm -rf crosswalks
mkdir -p crosswalks
for state in $STATES ; do 
  ofn=crosswalks/crosswalk_$state.csv 
  /bin/rm -f $ofn
  echo python3 crosswalk_generator.py --format csv --year 2010 --product sf1 --limit $LIMIT $SF1DIR/${state}geo2010.sf1 
       python3 crosswalk_generator.py --format csv --year 2010 --product sf1 --limit $LIMIT $SF1DIR/${state}geo2010.sf1 > $ofn </dev/null 2>&1 &
done
