#!/bin/bash
STATES="ak al ar az ca co ct dc de fl ga hi ia id il in ks ky la ma md me mi mn mo ms mt nc nd ne nh nj nm nv ny oh ok or pa ri sc sd tn tx ut va vt wa wi wv wy"
STATES='ak'
STATES="al ar az ca co ct dc de fl ga hi ia id il in ks ky la ma md me mi mn mo ms mt nc nd ne nh nj nm nv ny oh ok or pa ri sc sd tn tx ut va vt wa wi wv wy"
LIMIT=0
/bin/rm -rf crosswalks
mkdir -p crosswalks
for state in $STATES ; do 
  echo Launch $state
  ofn=crosswalks/crosswalk_$state.csv 
  /bin/rm -f $ofn
  python3 crosswalk_generator.py --format csv --year 2010 --product sf1 --limit $LIMIT  \
       ~/2010_sf1/geo/${state}geo2010.sf1 > $ofn </dev/null 2>&1 &
done
