# From http://mcdc.missouri.edu/cgi-bin/browse?/pub/sas/formats/Ssumlev.sas@
SUMLEVS = {
 '010':"United States",
 '020':"Region",
 '030':"Division",
 '040':"State ",
 '050':"County ",
 '060':"County Subdivision",
 '061':'MCD/CCD (10,000+)',
 '062':'MCD/CCD (<10,000)',
 '063':'MCD/CCD (2500+)',
 '064':'MCD/CCD (< 2500 in Metro Area)',
 '070':"County Subdivision-Place/Remainder",
 '071':"County Subdivision-Place (10,000+)/Remainder",
 '072':"County Subdivision-Place(2500+)/Remainder",
 '080':"County Subdivision-Place/Remainder-Census Tract",
 '082':"County Subdivision-Place(2500+)/Remainder-Census Tract",
 '085':"County Subdivision-Place/Remainder-Census Tract-Urban/Rural",
 '090':"County Subdivision-Place/Remainder-Census Tract-Urban/Rural-Block Group",
 '091':"County Subdivision-Place/Remainder-Census Tract-Block Group",
 '101':"Census Tract-Block",
 '067':"State (Puerto Rico Only)-County-County Subdivision-Subbarrio",
 '140':"Census Tract",
 '144':"Census Tract-American Indian Area/Alaska Native Area/Hawaiian Home Land",
 '150':"Census Tract-Block Group",
 '154':"Census Tract-Block Group-American Indian Area/Alaska Native Area/Hawaiian Home Land",
 '160':"Place",
 '161':'Place (10,000+)',
 '162':'Place (no CDPs)',

 '155':"Place-County",
 '157':"Place (no CDPs)-County",
 '158':"Place-County-Census Tract",
 '170':"Consolidated City",
 '172':"Consolidated City-Place Within Consolidated City",

 '200':'American Indian Resrvtn W Trust Lnds',
 '201':'American Indn Rsrvtn W Tr Lands: Rsrvtn Only',
 '202':'American Indian Resrvtns W Tr Lands:Tr Lands Only',
 '203':'American Ind Res No Tr Lnds/Tribal Jur Sa/Etc',
 '204':'American Ind Trust Lands (With No Reservation)',
 '205':'Am. Indn Rsrvtn W Tr Lnds:Rsrvtn Only-State',
 '206':'Am Indn Rsrvtn W Tr Lnds:Tr Lnds Only-State',
 '207':'Am Ind Res No Tr Lnds/Tribal Jur Sa/Etc-State',
 '208':'Am Indian Tr Lands (W. No Reservation)-State',
 '210':'State-Amer Indian Reservtn',
 '211':'State-Amer Indian Reservation Only',
 '212':'State-Amer Indian Rsrvtn Trust Land Only',
 '215':'State-Amer Indian Reservtn Jurisdiction',
 '216':'State-Amer Indiann Trust Lands',
 '220':'Amer Indian Reservtn Jurisdiction-Co',
 '221':'Amer Indian Trust Lands Only-Co',

 '230':"State-Alaska Native Regional Corporation",
 '250':"American Indian Area/Alaska Native Area/Hawaiian Home Land",
 '251':"American Indian Area/Alaska NativeArea/HawaiianHomeLand-Tribal Subdivision/Remainder",
 '252':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)4",
 '253':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-Tribal Subdivision/Remainder",
 '254':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land",
 '255':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-Tribal Subdivision/Remainder",
 '256':"Specified American Indian Area5-Tribal Census Tract6",
 '257':"Specified American Indian Area-Tribal Subdivision/Remainder-Tribal Census Tract",
 '258':"Specified American Indian Area-Tribal Census Tract-Tribal Block Group",
 '259':"Specified American Indian Area-Tribal Subdivision/Remainder-Tribal Census Tract-Tribal Block Group",

 '260':"American Indian Area/Alaska Native Area/Hawaiian Home Land-State",
 '261':"State-American IndianArea/Alaska Native Area/Hawaiian Home Land-County-County Subdivision",
 '262':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-State",
 '263':"State-American Indian Area/Alaska Native Area/Hawaiian Home Land-County-County Subdivision-Place/Remainder",

 '264':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-State",
 '269':"American Indian Area/Alaska Native Area/Hawaiian Home Land-Place-Remainder",
 '270':"American Indian Area/Alaska Native Area/Hawaiian Home Land-State-County",
 '271':"American Indian Area/Alaska Native Area/Hawaiian Home Land-State-County-County Subdivision",

 '272':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-State-County",
 '273':"American Indian Area/Alaska Native Area/Hawaiian Home Land-State- County-County Subdivision-Place/Remainder",
 '275':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-State-County-County Subdivision",
 '276':"American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-State-County-County Subdivision-Place/Remainder",

 '274':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land- State-County",
 '277':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land- State-County-County Subdivision",
 '278':"American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-State-County-County Subdivision-Place/Remainder",

 '280':"State-American Indian Area/Alaska Native Area/Hawaiian Home Land",
 '282':"State-American Indian Area/Alaska Native Area/Hawaiian Home Land-County",
 '283':"State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only) ",
 '285':"State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-County",
 '265':"State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-County-County Subdivision",
 '266':"State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-County-County Subdivision-Place/Remainder",
 '286':"State-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land",
 '288':"State-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-County",
 '267':"State-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-County-County Subdivision",
 '268':"State-American IndianArea (Off-Reservation Trust Land Only)/Hawaiian Home Land-County-County Subdivision-Place/Remainder",
 '281':"State-American Indian Area/Alaska Native Area/Hawaiian Home Land-Tribal Subdivision/Remainder",
 '284':"State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-Tribal Subdivision/Remainder",
 '287':"State-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-Tribal Subdivision/Remainder",
 '293':"Specified American Indian Area (Reservation or Statistical Entity Only)-Tribal Census Tract-Tribal Block Group",
 '294':"Specified American Indian Area (Off-Reservation Trust Land Only)-Tribal Census Tract-Tribal Block Group",
 '290':"American Indian Area/Alaska Native Area/Hawaiian Home Land-Tribal Subdivision/Remainder-State",

 '291':"Specified American Indian Area (Reservation or Statistical Entity Only)-Tribal Census Tract",
 '292':"Specified American Indian Area (Off-Reservation Trust Land Only)-Tribal Census Tract",

 '300':'MSA/CMSA:(CONSOLIDATED) METRO STATISTICAL AREA',
 '301':'PMSA: PRIMARY METRO STATISTICAL AREA ',

 '310':"CBSA", # Core Based Statistical Area, also known as Metropolitan/Micropolitan Statistical Areas
 '311':"CBSA-State",
 '312':"CBSA-State-Principal City",
 '313':"CBSA-State-County",
 '314':"Metropolitan Statistical Area/Metropolitan Division",
 '315':"Metropolitan Statistical Area/Metropolitan Division-State",
 '316':"Metropolitan Statistical Area/Metropolitan Division-State-County",

 '319':'State-MSA/CMSA',
 '320':"State- CBSA",
 '321':"State- CBSA -Principal City",
 '322':"State- CBSA -County",
 '323':"State- Metropolitan Statistical Area/Metropolitan Division",
 '324':"State- Metropolitan Statistical Area/Metropolitan Division-County",
 '329':"MSA(no CMSA's)-state-county",

 '330':"Combined Statistical Area",
 '331':"Combined Statistical Area-State",
 '332':"Combined Statistical Area-CBSA",
 '333':"Combined Statistical Area-CBSA-State",
 '335':"Combined New England City and Town Area",
 '336':"Combined New England City and Town Area -State",
 '337':"Combined New England City and Town Area -New England City and Town Area",
 '338':"Combined New England City and Town Area -New England City and Town Area-State",

 '340':"State-Combined Statistical Area",
 '341':"State-Combined Statistical Area-CBSA",
 '345':"State-Combined New England City and Town Area",
 '346':"State-Combined New England City and Town Area-New England City and Town Area",

 '350':"New England City and Town Area",
 '351':"New England City and Town Area-State",
 '352':"New England City and Town Area-State-Principal City",
 '353':"New England City and Town Area-State-County",
 '354':"New England City and Town Area-State-County-County Subdivision",
 '355':"New England City and Town Area (NECTA)-NECTA Division",
 '356':"New England City and Town Area (NECTA)-NECTA Division-State",
 '357':"New England City and Town Area (NECTA)-NECTA Division-State-County",
 '358':"New England City and Town Area (NECTA)-NECTA Division-State-County-County Subdivision",

 '360':"State-New England City and Town Area",
 '361':"State-New England City and Town Area-Principal City",
 '362':"State-New England City and Town Area-County",
 '363':"State-New England City and Town Area-County-County Subdivision",
 '364':"State-New England City and Town Area (NECTA)-NECTA Division",
 '365':"State-New England City and Town Area (NECTA)-NECTA Division-County",
 '366':"State-New England City and Town Area (NECTA)-NECTA Division-County-County Subdivision",

 '370':"New England County Metropolitan Area",
 '371':"New England County Metropolitan Area-State",
 '372':"New England County Metropolitan Area-State-Central City",
 '373':"New England County Metropolitan Area-State-County",
 '374':"State-New England County Metropolitan Area",
 '375':"State-New England County Metropolitan Area-Central City",
 '376':"State-New England County Metropolitan Area-County",

 '380':"Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area",
 '381':"Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-State",
 '382':"Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-State-Central City",
 '383':"Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-State-County",
 '384':"Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-State (New England only)-County-County Subdivision",
 '385':"Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area",
 '386':"Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area-State",
 '387':"Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area-State-County",
 '388':"Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area-State (New England only)-County-County Subdivision",

 '390':"State-Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area",
 '391':"State-Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-Central City",
 '392':"State-Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-County",
 '393':"State (New England  only)-Metropolitan Statistical Area/Consolidated Metropolitan Statistical Area-County-County Subdivision",
 '395':"State-Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area",
 '396':"State-Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area-County",
 '397':"State (New England only) Consolidated Metropolitan Statistical Area-Primary Metropolitan Statistical Area-County-County Subdivision",

 '400':"Urban Area",
 '410':"Urban Area-State",
 '420':"State-Urban Area",
 '430':"Urban Area-State-County",
 '431':"State-Urban Area-County",
 '440':"Urban Area-State-County-County Subdivision",
 '441':"State-Urban Area-County-County Subdivision",
 '450':"Urban Area-State-County-County Subdivision-Place/Remainder",
 '451':"State-Urban Area-County-County Subdivision-Place/Remainder",
 '460':"Urban Area-State-Central Place",
 '461':"State-Urban Area-Central Place",
 '462':"Urban Area-State-Consolidated City",
 '463':"State-Urban Area-Consolidated City",
 '464':"Urban Area-State-Consolidated City-Place",

 '500':"Congressional District ",
 '510':"Congressional District-County",
 '511':"Congressional District-County-Census Tract",
 '521':"Congressional District-County-County Subdivision",
 '531':"Congressional District-Place/Remainder",
 '541':"Congressional District-Consolidated City",
 '542':"Congressional District-Consolidated City-Place Within Consolidated City",
 '550':"Congressional District-American IndianArea/Alaska NativeArea/Hawaiian Home Land",
 '551':"Congressional District-American Indian Area/Alaska Native Area(Reservation or Statistical Entity Only)",
 '552':"Congressional District-American Indian Area (Off-Reservation Trust Land only)/Hawaiian Home Land",
 '553':"Congressional District-American Indian Area/Alaska Native Area/Hawaiian Home Land-Tribal Subdivision/Remainder",
 '554':"Congressional District-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)-Tribal Subdivision/Remainder",
 '555':"Congressional District-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land-Tribal Subdivision/Remainder",
 '560':"Congressional District-Alaska Native Regional Corporation ",

 '610':"State Senate District",
 '612':"State Senate District-County",
 '613':"State Senate District-County-MCD-Place",
 '614':"State Senate District-Place",
 '620':"State House District",
 '622':"State House District-County",
 '623':"State House District-County-MCD-Place",
 '624':"State House District-Place",

 '700':"VTD (Voting Tabulation District)",
 '740':"Block Group, split by VTD, MCD, and Place",
 '750':"Census Block (pl94 files)",

 '795':"State-Public Use MicroSample Area 5%",
 '850':"3-digit ZIP Code Tabulation Area",
 '851':"State-3-Digit ZIP Code Tabulation Area",
 '852':"State-3-digit ZIP Code Tabulation Area-County",
 '860':"5-digit ZIP Code Tabulation Area",
 '870':"5-digit ZIP Code Tabulation Area-State",
 '871':"State-5-digit ZIP Code Tabulation Area",
 '880':"5-digit ZIP Code Tabulation Area-County",
 '881':"State-5-digit ZIP Code Tabulation Area-County",
 '901':"County Set",
 '930':"Metropolitan Planning Org. Region (CTPP)",
 '935':"State-County-Combined Zone (CTPP)",
 '940':"State-County-Traffic Analysis Zone (CTPP)",
    
 '950':"State-Elementary School District",
 '960':"State-High School District",
 '970':"State-Unified School District"
}
