mem:
	python 03_synth_lp_files.py --mem ak 013 000100

mem2:
	python 03_synth_lp_files.py --mem de 001 040100 

mem3:
	python 03_synth_lp_files.py --mem de 001 040100 

clean:
	/bin/rm -f *.log *.dfxml

setuptest:
	mkdir -p /data/sf1/recon_test/al
	cp /data/sf1/recon/al/*.csv /data/sf1/recon_test/al/
